# Generated by Django 2.2 on 2020-05-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('Favorite_Sandwich', models.CharField(max_length=20)),
                ('Bio', models.CharField(max_length=500)),
            ],
        ),
    ]
